---
- hosts: all
  become: true
  tasks:

  - name: install apache and php packages
    package:
      name:
        - "{{ python_package }}"
        - "{{ pip_package }}"
      state: latest
      update_cache: yes
